version: "3.8"

services:
  # MongoDB for conversation storage
  mongodb:
    image: mongo:7.0
    container_name: mental-health-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mental_health_chat
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mental-health-network

  # Redis for caching and sessions
  redis:
    image: redis:7.2-alpine
    container_name: mental-health-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mental-health-network

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: mental-health-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - mental-health-network
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  mental-health-network:
    driver: bridge
